#!/bin/sh

if [ -e /var/clearos/flexshare/initialized ]; then
    logger -p local6.notice -t installer "app-flexshare-core - removing initialized file"
    rm -f /var/clearos/flexshare/initialized
fi

