#!/bin/sh

# Add flexshares user
#--------------------

getent group flexshares >/dev/null || groupadd -r flexshares
getent passwd flexshares >/dev/null || \
    useradd -r -g flexshares -d /var/flexshares -s /sbin/nologin -c "Flexshares" flexshares

# Make sure directory ownership is correct on upgrade
#----------------------------------------------------

DIR="/var/flexshare/shares"

CHECKPERMS=`stat --format=%a $DIR`
if [ "$CHECKPERMS" != "755" ]; then
    logger -p local6.notice -t installer "app-flexshare-core - updating file permissions of $DIR"
    chmod 755 $DIR
fi

CHECKOWNERSHIP=`stat --format=%U.%G $DIR`
if [ "$CHECKOWNERSHIP" != "root.root" ]; then
    logger -p local6.notice -t installer "app-flexshare-core - updating file ownership on $DIR"
    chown root.root $DIR
fi

# Run PHP upgrade script
#-----------------------

/usr/clearos/apps/flexshare/deploy/upgrade-api
