#!/bin/sh

# Sanity check parameters
#------------------------

if ( [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ] ); then
	echo "usage: $0 <flexshare-path> <owner> <group> <perms>"
	exit 1
fi

SANITY_CHECK=`grep "^[[:space:]]*ShareDir=$1$" /etc/clearos/flexshare.conf /etc/clearos/flexshare.d/*.conf 2>/dev/null`

if [ -z "$SANITY_CHECK" ]; then
	echo "flexshare is invalid: $1"
	exit 1
fi

# Set file permissions
#---------------------

USER=$2
GROUP=$3
DIR_PERMS=$4

chown $USER.$GROUP "$1"
chmod $DIR_PERMS "$1"

find $1 -not -group $GROUP -not -name .flexshare-* -exec chgrp $GROUP '{}' \;

# Cosmetic - change .trash folder owner
#--------------------------------------

if [ -d "$1/.trash" ]; then
	chmod $DIR_PERMS "$1/.trash"
fi
